name: Release Image
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      -
        name: Build and push hub-credentials
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: holaplex/hub-credentials:${{ github.sha }},holaplex/hub-credentials:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: Invoke workflow in hub-kubes repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }}
          workflow: release.yml
          repo: holaplex/hub-kubes
          inputs: '{ "service": "credentials", "environment": "stage", "commit_hash": "${{ github.sha }}"}'
